import type { AuthBgKey } from '@/context/ThemeContext';

export type RangeControl  = { type: 'range';  key: string; label: string; min: number; max: number; step: number; default: number };
export type SelectControl = { type: 'select'; key: string; label: string; options: { label: string; value: string }[]; default: string };
export type ToggleControl = { type: 'toggle'; key: string; label: string; default: boolean };
export type ColorControl  = { type: 'color';  key: string; label: string; default: string };
export type ControlDef = RangeControl | SelectControl | ToggleControl | ColorControl;

const BG: ColorControl = { type: 'color', key: 'bgColor', label: 'Cor de Fundo', default: 'auto' };

export const EFFECT_CONTROLS: Partial<Record<AuthBgKey, ControlDef[]>> = {
  'dark-veil': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 3, step: 0.1, default: 0.5 },
    { type: 'range', key: 'hueShift', label: 'Hue Shift', min: 0, max: 360, step: 5, default: 0 },
    { type: 'range', key: 'noiseIntensity', label: 'Noise Intensity', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'warpAmount', label: 'Warp Amount', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'scanlineIntensity', label: 'Scanline Intensity', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'scanlineFrequency', label: 'Scanline Frequency', min: 0, max: 500, step: 10, default: 0 },
    { type: 'range', key: 'resolutionScale', label: 'Resolution Scale', min: 0.25, max: 2, step: 0.25, default: 1 },
  ],
  'soft-aurora': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 2, step: 0.1, default: 0.6 },
    { type: 'range', key: 'brightness', label: 'Brightness', min: 0.5, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'noiseFrequency', label: 'Noise Frequency', min: 1, max: 8, step: 0.5, default: 2.5 },
    { type: 'range', key: 'noiseAmplitude', label: 'Noise Amplitude', min: 0.1, max: 1.5, step: 0.1, default: 1 },
    { type: 'range', key: 'bandSpread', label: 'Band Spread', min: 0.5, max: 2, step: 0.1, default: 1 },
  ],
  'aurora': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'amplitude', label: 'Amplitude', min: 0.1, max: 3, step: 0.1, default: 1.2 },
    { type: 'range', key: 'blend', label: 'Blend', min: 0, max: 1, step: 0.05, default: 0.5 },
  ],
  'iridescence': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 5, step: 0.1, default: 0.8 },
    { type: 'range', key: 'amplitude', label: 'Amplitude', min: 0.01, max: 0.5, step: 0.01, default: 0.15 },
  ],
  'silk': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.5, max: 15, step: 0.5, default: 5 },
    { type: 'range', key: 'scale', label: 'Scale', min: 0.5, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'noiseIntensity', label: 'Noise Intensity', min: 0.1, max: 3, step: 0.1, default: 1.5 },
    { type: 'range', key: 'rotation', label: 'Rotation', min: 0, max: 360, step: 5, default: 0 },
  ],
  'color-bends': [ BG,
    { type: 'range', key: 'rotation', label: 'Rotation', min: 0, max: 360, step: 5, default: 45 },
    { type: 'range', key: 'speed', label: 'Speed', min: 0.05, max: 1, step: 0.05, default: 0.2 },
    { type: 'range', key: 'scale', label: 'Scale', min: 0.5, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'frequency', label: 'Frequency', min: 0.5, max: 4, step: 0.1, default: 1 },
    { type: 'range', key: 'warpStrength', label: 'Warp Strength', min: 0, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'noise', label: 'Noise', min: 0, max: 0.5, step: 0.01, default: 0.1 },
    { type: 'range', key: 'mouseInfluence', label: 'Mouse Influence', min: 0, max: 2, step: 0.1, default: 1 },
    { type: 'range', key: 'parallax', label: 'Parallax', min: 0, max: 1, step: 0.1, default: 0.5 },
  ],
  'pixel-blast': [ BG,
    { type: 'select', key: 'variant', label: 'Variant', options: [{ label: 'Square', value: 'square' }, { label: 'Circle', value: 'circle' }], default: 'square' },
    { type: 'range', key: 'pixelSize', label: 'Pixel Size', min: 1, max: 20, step: 1, default: 4 },
    { type: 'range', key: 'patternScale', label: 'Pattern Scale', min: 0.5, max: 5, step: 0.1, default: 2 },
    { type: 'range', key: 'patternDensity', label: 'Pattern Density', min: 0.1, max: 1, step: 0.05, default: 1 },
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 3, step: 0.1, default: 0.5 },
    { type: 'range', key: 'edgeFade', label: 'Edge Fade', min: 0, max: 1, step: 0.05, default: 0.25 },
    { type: 'toggle', key: 'enableRipples', label: 'Enable Ripples', default: true },
    { type: 'range', key: 'rippleSpeed', label: 'Ripple Speed', min: 0.1, max: 2, step: 0.1, default: 0.4 },
    { type: 'range', key: 'rippleThickness', label: 'Ripple Thickness', min: 0.01, max: 0.5, step: 0.01, default: 0.12 },
    { type: 'range', key: 'rippleIntensityScale', label: 'Ripple Intensity', min: 0.1, max: 3, step: 0.1, default: 1.5 },
  ],
  'beams': [ BG,
    { type: 'range', key: 'rippleShadow',   label: 'Sombra da Ondulação', min: 0, max: 3,    step: 0.05, default: 1.0 },
    { type: 'range', key: 'colorIntensity', label: 'Intensidade da Cor',  min: 0.1, max: 3,  step: 0.05, default: 1.6 },
    { type: 'range', key: 'vignette',       label: 'Sombra nas Bordas',   min: 0, max: 3,    step: 0.05, default: 1.0 },
    { type: 'range', key: 'beamWidth',      label: 'Beam Width',          min: 0.5, max: 8,  step: 0.5,  default: 2 },
    { type: 'range', key: 'beamHeight',     label: 'Beam Height',         min: 5, max: 40,   step: 1,    default: 21 },
    { type: 'range', key: 'beamNumber',     label: 'Beam Count',          min: 2, max: 30,   step: 1,    default: 11 },
    { type: 'range', key: 'speed',          label: 'Speed',               min: 0.5, max: 8,  step: 0.1,  default: 8 },
    { type: 'range', key: 'noiseIntensity', label: 'Noise Intensity',     min: 0, max: 3,    step: 0.05, default: 1.6 },
    { type: 'range', key: 'scale',          label: 'Scale',               min: 0.05, max: 0.5, step: 0.01, default: 0.27 },
    { type: 'range', key: 'rotation',       label: 'Rotation',            min: -180, max: 180, step: 5,  default: 0 },
  ],
  'gradient-blinds': [ BG,
    { type: 'range', key: 'blindCount', label: 'Blind Count', min: 2, max: 24, step: 1, default: 12 },
    { type: 'range', key: 'angle', label: 'Angle', min: -3.14, max: 3.14, step: 0.1, default: 0 },
    { type: 'range', key: 'noise', label: 'Noise', min: 0, max: 0.5, step: 0.01, default: 0.05 },
    { type: 'range', key: 'spotlightRadius', label: 'Spotlight Radius', min: 0.1, max: 1, step: 0.05, default: 0.5 },
    { type: 'range', key: 'spotlightSoftness', label: 'Softness', min: 0.5, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'spotlightOpacity', label: 'Opacity', min: 0, max: 1, step: 0.05, default: 1 },
    { type: 'range', key: 'mouseDampening', label: 'Mouse Dampening', min: 0.05, max: 1, step: 0.05, default: 0.15 },
  ],
  'liquid-ether': [ BG,
    { type: 'range', key: 'mouseForce', label: 'Mouse Force', min: 1, max: 200, step: 1, default: 60 },
    { type: 'range', key: 'cursorSize', label: 'Cursor Size', min: 10, max: 300, step: 10, default: 100 },
    { type: 'range', key: 'autoSpeed', label: 'Auto Speed', min: 0.1, max: 2, step: 0.1, default: 0.8 },
    { type: 'range', key: 'autoIntensity', label: 'Auto Intensity', min: 0.5, max: 8, step: 0.1, default: 4.0 },
    { type: 'range', key: 'resolution', label: 'Resolution', min: 0.25, max: 1, step: 0.25, default: 0.5 },
  ],
  'plasma': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'scale', label: 'Scale', min: 0.5, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'opacity', label: 'Opacity', min: 0.1, max: 1, step: 0.05, default: 0.9 },
  ],
  'line-waves': [ BG,
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 2, step: 0.1, default: 0.3 },
    { type: 'range', key: 'innerLineCount', label: 'Inner Lines', min: 4, max: 64, step: 2, default: 32 },
    { type: 'range', key: 'outerLineCount', label: 'Outer Lines', min: 4, max: 64, step: 2, default: 36 },
    { type: 'range', key: 'warpIntensity', label: 'Warp Intensity', min: 0, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'rotation', label: 'Rotation', min: -180, max: 180, step: 5, default: -45 },
    { type: 'range', key: 'edgeFadeWidth', label: 'Edge Fade', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'colorCycleSpeed', label: 'Color Cycle Speed', min: 0, max: 5, step: 0.1, default: 1 },
    { type: 'range', key: 'brightness', label: 'Brightness', min: 0.05, max: 2, step: 0.05, default: 0.2 },
    { type: 'range', key: 'mouseInfluence', label: 'Mouse Influence', min: 0, max: 5, step: 0.1, default: 2 },
  ],
  'light-rays': [ BG,
    { type: 'select', key: 'raysOrigin', label: 'Origin', options: [{ label:'Top Center',value:'top-center'},{ label:'Top Left',value:'top-left'},{ label:'Top Right',value:'top-right'},{ label:'Left',value:'left'},{ label:'Right',value:'right'},{ label:'Bottom Center',value:'bottom-center'}], default: 'top-center' },
    { type: 'range', key: 'raysSpeed', label: 'Speed', min: 0.1, max: 5, step: 0.1, default: 1 },
    { type: 'range', key: 'lightSpread', label: 'Light Spread', min: 0.1, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'rayLength', label: 'Ray Length', min: 0.5, max: 5, step: 0.1, default: 2 },
    { type: 'range', key: 'fadeDistance', label: 'Fade Distance', min: 0.1, max: 2, step: 0.1, default: 1 },
    { type: 'range', key: 'saturation', label: 'Saturation', min: 0, max: 2, step: 0.1, default: 1 },
    { type: 'toggle', key: 'pulsating', label: 'Pulsating', default: false },
    { type: 'range', key: 'mouseInfluence', label: 'Mouse Influence', min: 0, max: 0.5, step: 0.01, default: 0.1 },
    { type: 'range', key: 'noiseAmount', label: 'Noise Amount', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'distortion', label: 'Distortion', min: 0, max: 1, step: 0.05, default: 0 },
  ],
  'light-pillar': [ BG,
    { type: 'range', key: 'intensity', label: 'Intensity', min: 0.1, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'rotationSpeed', label: 'Rotation Speed', min: 0, max: 2, step: 0.1, default: 0.3 },
    { type: 'range', key: 'pillarWidth', label: 'Pillar Width', min: 0.5, max: 10, step: 0.5, default: 3 },
    { type: 'range', key: 'pillarHeight', label: 'Pillar Height', min: 0.1, max: 1, step: 0.05, default: 0.4 },
    { type: 'range', key: 'glowAmount', label: 'Glow Amount', min: 0, max: 0.05, step: 0.001, default: 0.005 },
    { type: 'range', key: 'noiseIntensity', label: 'Noise Intensity', min: 0, max: 2, step: 0.1, default: 0.5 },
  ],
  'orb': [ BG,
    { type: 'range', key: 'hue', label: 'Hue', min: 0, max: 360, step: 5, default: 0 },
    { type: 'range', key: 'hoverIntensity', label: 'Hover Intensity', min: 0, max: 1, step: 0.05, default: 0.5 },
  ],
  'dot-grid': [ BG,
    { type: 'range', key: 'dotSize', label: 'Dot Size', min: 2, max: 20, step: 1, default: 4 },
    { type: 'range', key: 'gap', label: 'Gap', min: 8, max: 60, step: 2, default: 22 },
    { type: 'range', key: 'proximity', label: 'Proximity', min: 50, max: 400, step: 10, default: 230 },
    { type: 'range', key: 'speedTrigger', label: 'Speed Trigger', min: 10, max: 500, step: 10, default: 100 },
    { type: 'range', key: 'shockRadius', label: 'Shock Radius', min: 50, max: 500, step: 10, default: 250 },
    { type: 'range', key: 'shockStrength', label: 'Shock Strength', min: 1, max: 20, step: 1, default: 5 },
    { type: 'range', key: 'resistance', label: 'Resistance', min: 100, max: 2000, step: 50, default: 750 },
    { type: 'range', key: 'returnDuration', label: 'Return Duration', min: 0.2, max: 3, step: 0.1, default: 1.5 },
    { type: 'range', key: 'maxSpeed', label: 'Max Speed', min: 500, max: 10000, step: 500, default: 5000 },
  ],
  'prism': [ BG,
    { type: 'select', key: 'animationType', label: 'Animation', options: [{ label:'Rotate',value:'rotate'},{ label:'3D Rotate',value:'3drotate'},{ label:'Hover',value:'hover'}], default: 'rotate' },
    { type: 'range', key: 'height', label: 'Height', min: 0.5, max: 8, step: 0.5, default: 3.5 },
    { type: 'range', key: 'baseWidth', label: 'Base Width', min: 1, max: 10, step: 0.5, default: 5.5 },
    { type: 'range', key: 'glow', label: 'Glow', min: 0, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'bloom', label: 'Bloom', min: 0, max: 3, step: 0.1, default: 1 },
    { type: 'range', key: 'noise', label: 'Noise', min: 0, max: 1, step: 0.05, default: 0.5 },
    { type: 'range', key: 'scale', label: 'Scale', min: 0.5, max: 8, step: 0.1, default: 3.6 },
    { type: 'range', key: 'hueShift', label: 'Hue Shift', min: -3.14, max: 3.14, step: 0.1, default: 0 },
    { type: 'range', key: 'colorFrequency', label: 'Color Frequency', min: 0.1, max: 5, step: 0.1, default: 1 },
    { type: 'range', key: 'timeScale', label: 'Time Scale', min: 0, max: 2, step: 0.1, default: 0.5 },
    { type: 'range', key: 'hoverStrength', label: 'Hover Strength', min: 0, max: 5, step: 0.1, default: 2 },
    { type: 'range', key: 'inertia', label: 'Inertia', min: 0.01, max: 0.5, step: 0.01, default: 0.05 },
  ],
  'prismatic-burst': [ BG,
    { type: 'select', key: 'animationType', label: 'Animation', options: [{ label:'Rotate',value:'rotate'},{ label:'3D Rotate',value:'rotate3d'},{ label:'Hover',value:'hover'}], default: 'rotate3d' },
    { type: 'range', key: 'intensity', label: 'Intensity', min: 0.5, max: 5, step: 0.1, default: 2 },
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 3, step: 0.1, default: 0.5 },
    { type: 'range', key: 'distort', label: 'Distort', min: 0, max: 20, step: 0.5, default: 0 },
    { type: 'range', key: 'hoverDampness', label: 'Hover Dampness', min: 0, max: 1, step: 0.05, default: 0 },
    { type: 'range', key: 'rayCount', label: 'Ray Count', min: 0, max: 20, step: 1, default: 0 },
  ],
  'shape-grid': [ BG,
    { type: 'select', key: 'shape', label: 'Shape', options: [{ label:'Square',value:'square'},{ label:'Circle',value:'circle'},{ label:'Hexagon',value:'hexagon'},{ label:'Triangle',value:'triangle'}], default: 'square' },
    { type: 'select', key: 'direction', label: 'Direction', options: [{ label:'Right',value:'right'},{ label:'Left',value:'left'},{ label:'Up',value:'up'},{ label:'Down',value:'down'},{ label:'Diagonal',value:'diagonal'}], default: 'diagonal' },
    { type: 'range', key: 'squareSize', label: 'Cell Size', min: 20, max: 100, step: 4, default: 40 },
    { type: 'range', key: 'speed', label: 'Speed', min: 0.1, max: 5, step: 0.1, default: 0.5 },
    { type: 'range', key: 'hoverTrailAmount', label: 'Trail Amount', min: 0, max: 20, step: 1, default: 0 },
  ],
};

export const getDefaultConfig = (bg: AuthBgKey): Record<string, number | string | boolean> => {
  const controls = EFFECT_CONTROLS[bg] ?? [];
  return Object.fromEntries(controls.map(c => [c.key, c.default]));
};
